### ISSUE TITLE
Docker Question

### ISSUE THREAD

**Issue by Isabeljason** [docker/community#93]
By '[Dockerizing](https://mindmajix.com/docker-training)' what is the benefit? and how it could be explained in detail.

**Comment by gesellix** [comment]
Maybe a GitHub issue is not the best place to ask, you might want to ask the community via forum, slack or other channels. See https://www.docker.com/docker-community for an overview.

To actually give a little answer to your question: I guess this article sums up quite well what happens when one tries to Dockerize services: https://nothingventured.rocks/phorest-migrated-to-docker-and-this-is-what-happened-8f0752ada960 - in essence: Dockerizing makes you review your architecture and application design and gives you a good options to improve the status quo.

**Comment by Isabeljason** [comment]
The article is very helpful thankyou

**Comment by vcoisne** [comment]
Thanks @gesellix for your help.
